package com.questkeeper.listener;

import com.questkeeper.gui.*; import com.questkeeper.message.MessageManager; import com.questkeeper.npc.NpcManager; import com.questkeeper.quest.QuestManager; import com.questkeeper.quest.model.*; import com.questkeeper.quest.service.*; import org.bukkit.*; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.block.*; import org.bukkit.event.entity.*; import org.bukkit.event.inventory.*; import org.bukkit.event.player.*; import org.bukkit.inventory.ItemStack; import org.bukkit.plugin.java.JavaPlugin; import java.util.*;

public final class QuestListener implements Listener {
    private final JavaPlugin plugin; private final NpcManager npcs; private final QuestManager quests; private final GuiManager guis; private final QuestProgressService progress; private final QuestClaimService claims; private final PlayerQuestDataService data; private final QuestStateService states; private final MessageManager messages; private final Set<String> placedBlocks=Collections.synchronizedSet(new HashSet<>());
    public QuestListener(JavaPlugin p,NpcManager n,QuestManager q,GuiManager g,QuestProgressService pr,QuestClaimService c,PlayerQuestDataService d,QuestStateService st,MessageManager m){plugin=p;npcs=n;quests=q;guis=g;progress=pr;claims=c;data=d;states=st;messages=m;}
    @EventHandler public void join(PlayerJoinEvent e){data.load(e.getPlayer());}
    @EventHandler public void quit(PlayerQuitEvent e){data.saveAndRemove(e.getPlayer().getUniqueId());}
    @EventHandler public void npcInteract(PlayerInteractEntityEvent e){if(!npcs.isNpc(e.getRightClicked()))return;e.setCancelled(true);Player p=e.getPlayer();var n=npcs.from(e.getRightClicked());for(String line:n.greeting())p.sendMessage(net.kyori.adventure.text.minimessage.MiniMessage.miniMessage().deserialize(line));for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.INTERACT_NPC&&o.settings().getOrDefault("npc-id","").toString().equalsIgnoreCase(n.id()))progress.add(p,q.id(),o.id(),1);guis.openNpc(p,n.id());}
    @EventHandler public void protect(EntityDamageEvent e){if(npcs.isNpc(e.getEntity()))e.setCancelled(true);}
    @EventHandler public void protectTarget(EntityTargetEvent e){if(npcs.isNpc(e.getEntity()))e.setCancelled(true);}
    @EventHandler public void inventoryClick(InventoryClickEvent e){if(!(e.getInventory().getHolder() instanceof MainQuestHolder)&&!(e.getInventory().getHolder() instanceof DetailQuestHolder)&&!(e.getInventory().getHolder() instanceof JournalHolder))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||e.getRawSlot()<0)return;if(e.getInventory().getHolder() instanceof MainQuestHolder h){if(e.getRawSlot()==48){p.closeInventory();return;}if(e.getRawSlot()==45&&h.page>0){guis.openNpc(p,h.npcId,h.page-1);return;}if(e.getRawSlot()==53){guis.openNpc(p,h.npcId,h.page+1);return;}String id=h.quests.get(e.getRawSlot());if(id!=null)guis.openDetails(p,id,h.npcId);}else if(e.getInventory().getHolder() instanceof DetailQuestHolder h){if(e.getRawSlot()==18){guis.openNpc(p,h.npcId);return;}Quest q=quests.get(h.questId);if(q==null)return;QuestStatus status=states.state(p,q);if(e.getRawSlot()==22){if(status==QuestStatus.AVAILABLE)claims.accept(p,q.id());else if(status==QuestStatus.READY_TO_CLAIM)claims.claim(p,q.id(),h.npcId);else if(status==QuestStatus.ACTIVE)claims.cancel(p,q.id());guis.openDetails(p,q.id(),h.npcId);}}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getInventory().getHolder() instanceof MainQuestHolder||e.getInventory().getHolder() instanceof DetailQuestHolder||e.getInventory().getHolder() instanceof JournalHolder)e.setCancelled(true);}
    @EventHandler public void kill(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p==null)return;for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.KILL_ENTITY&&o.settings().getOrDefault("entity","").toString().equalsIgnoreCase(e.getEntityType().name()))progress.add(p,q.id(),o.id(),1);}
    @EventHandler public void blockPlace(BlockPlaceEvent e){placedBlocks.add(key(e.getBlock().getLocation()));for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.PLACE_BLOCK&&o.settings().getOrDefault("material","").toString().equalsIgnoreCase(e.getBlock().getType().name()))progress.add(e.getPlayer(),q.id(),o.id(),1);}
    @EventHandler public void blockBreak(BlockBreakEvent e){String key=key(e.getBlock().getLocation());boolean placed=placedBlocks.remove(key);for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.BREAK_BLOCK&&o.settings().getOrDefault("material","").toString().equalsIgnoreCase(e.getBlock().getType().name())&&(!placed||Boolean.TRUE.equals(o.settings().get("count-player-placed-blocks"))))progress.add(e.getPlayer(),q.id(),o.id(),1);}
    @EventHandler public void craft(CraftItemEvent e){if(!(e.getWhoClicked() instanceof Player p))return;int amount=e.isShiftClick()?e.getRecipe().getResult().getMaxStackSize():e.getCurrentItem().getAmount();for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.CRAFT_ITEM&&o.settings().getOrDefault("material","").toString().equalsIgnoreCase(e.getRecipe().getResult().getType().name()))progress.add(p,q.id(),o.id(),amount);}
    @EventHandler public void pickup(EntityPickupItemEvent e){if(!(e.getEntity() instanceof Player p))return;ItemStack stack=e.getItem().getItemStack();for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.COLLECT_ITEM&&o.settings().getOrDefault("material","").toString().equalsIgnoreCase(stack.getType().name()))progress.add(p,q.id(),o.id(),stack.getAmount());}
    @EventHandler public void command(PlayerCommandPreprocessEvent e){String command=e.getMessage().substring(1).split(" ",2)[0].toLowerCase(Locale.ROOT);for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.EXECUTE_COMMAND&&o.settings().getOrDefault("command","").toString().replace("/","").equalsIgnoreCase(command))progress.add(e.getPlayer(),q.id(),o.id(),1);}
    @EventHandler public void reach(PlayerMoveEvent e){if(e.getTo()==null||e.getFrom().distanceSquared(e.getTo())<1.0)return;Player p=e.getPlayer();for(Quest q:quests.all())for(var o:q.objectives().values())if(o.type()==ObjectiveType.REACH_LOCATION){String world=o.settings().getOrDefault("world","").toString();if(!world.isBlank()&&!p.getWorld().getName().equalsIgnoreCase(world))continue;double x=number(o.settings().get("x")),y=number(o.settings().get("y")),z=number(o.settings().get("z")),radius=number(o.settings().getOrDefault("radius",2));if(p.getLocation().distanceSquared(new Location(p.getWorld(),x,y,z))<=radius*radius)progress.add(p,q.id(),o.id(),o.amount());}}
    private double number(Object value){return value instanceof Number n?n.doubleValue():0.0;}
    private String key(Location l){return l.getWorld().getName()+":"+l.getBlockX()+":"+l.getBlockY()+":"+l.getBlockZ();}
}
