package com.questkeeper.gui;

import com.questkeeper.message.MessageManager; import com.questkeeper.npc.NpcManager; import com.questkeeper.quest.QuestManager; import com.questkeeper.quest.model.*; import com.questkeeper.quest.service.*; import net.kyori.adventure.text.Component; import net.kyori.adventure.text.minimessage.MiniMessage; import org.bukkit.*; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.entity.Player; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import org.bukkit.plugin.java.JavaPlugin; import java.io.File; import java.util.*;

public final class GuiManager {
    private final JavaPlugin plugin; private final QuestManager quests; private final NpcManager npcs; private final QuestStateService states; private final QuestProgressService progress; private final RequirementService requirements; private final MessageManager messages; private final MiniMessage mini=MiniMessage.miniMessage();
    public GuiManager(JavaPlugin p,QuestManager q,NpcManager n,QuestStateService s,QuestProgressService pr,RequirementService req,MessageManager m){plugin=p;quests=q;npcs=n;states=s;progress=pr;requirements=req;messages=m;}
    public void openNpc(Player p,String npcId){openNpc(p,npcId,0);}
    public void openNpc(Player p,String npcId,int page){var n=npcs.get(npcId);if(n==null)return;MainQuestHolder holder=new MainQuestHolder(npcId,page);Inventory inv=Bukkit.createInventory(holder,54,messages.component("<gold>Quests: <yellow>"+n.displayName()+"</yellow>",Map.of()));holder.inventory(inv);int index=0,start=page*45;for(String id:n.quests()){Quest q=quests.get(id);if(q==null||index<start){if(q!=null)index++;continue;}if(index>=start+45)break;holder.quests.put(10+(index-start)%9+(index-start)/9*9,id);inv.setItem(10+(index-start)%9+(index-start)/9*9,item(materialFor(states.state(p,q)),q.displayName(),lore(p,q)));index++;}inv.setItem(45,item(Material.ARROW,"<yellow>Previous",List.of()));inv.setItem(49,item(Material.NETHER_STAR,"<aqua>Refresh",List.of()));inv.setItem(53,item(Material.ARROW,"<yellow>Next",List.of()));inv.setItem(48,item(Material.BARRIER,"<red>Close",List.of()));p.openInventory(inv);}
    public void openJournal(Player p){JournalHolder h=new JournalHolder();Inventory inv=Bukkit.createInventory(h,54,mini.deserialize("<gold>Your Quest Journal"));h.inventory(inv);int slot=10;for(Quest q:quests.all()){if(slot>=44)break;h.getInventory().setItem(slot++,item(materialFor(states.state(p,q)),q.displayName(),lore(p,q)));}p.openInventory(inv);}
    public void openDetails(Player p,String questId,String npcId){Quest q=quests.get(questId);if(q==null)return;DetailQuestHolder h=new DetailQuestHolder(questId,npcId);Inventory inv=Bukkit.createInventory(h,27,mini.deserialize(q.displayName()));h.inventory(inv);inv.setItem(4,item(Material.matchMaterial(q.iconMaterial()),q.displayName(),q.description()));List<String> objectiveLore=new ArrayList<>();for(var o:q.objectives().values())objectiveLore.add(mini.serialize(component(o.display(),Map.of("progress",String.valueOf(progress.progress(p,q,o.id())),"required",String.valueOf(o.amount())))));inv.setItem(10,item(Material.WRITABLE_BOOK,"<yellow>Objectives",objectiveLore));List<String> req= new ArrayList<>(requirements.missing(p,q));if(req.isEmpty())req.add("<green>All requirements met");inv.setItem(12,item(Material.PAPER,"<yellow>Requirements",req));inv.setItem(14,item(Material.CHEST,"<yellow>Rewards",q.rewards().stream().map(r->"<white>"+r.type()+" " + r.amount()).toList()));QuestStatus status=states.state(p,q);inv.setItem(16,item(Material.PAPER,"<yellow>Status: <white>"+status,List.of()));if(status==QuestStatus.AVAILABLE)inv.setItem(22,item(Material.LIME_DYE,"<green>Accept Quest",List.of()));if(status==QuestStatus.READY_TO_CLAIM)inv.setItem(22,item(Material.CHEST,"<green>Claim Reward",List.of()));if(status==QuestStatus.ACTIVE&&q.allowCancel())inv.setItem(22,item(Material.RED_DYE,"<red>Cancel Quest",List.of()));inv.setItem(18,item(Material.OAK_DOOR,"<yellow>Back",List.of()));p.openInventory(inv);}
    private List<String> lore(Player p,Quest q){List<String> l=new ArrayList<>(q.description());l.add("<yellow>Objectives:");for(var o:q.objectives().values())l.add(o.display().replace("%progress%",String.valueOf(progress.progress(p,q,o.id()))).replace("%required%",String.valueOf(o.amount())));l.add("<yellow>Status: <white>"+states.state(p,q));return l;}
    private Material materialFor(QuestStatus status){return switch(status){case AVAILABLE->Material.WRITABLE_BOOK;case ACTIVE->Material.CLOCK;case READY_TO_CLAIM->Material.CHEST;case COMPLETED->Material.LIME_DYE;case LOCKED->Material.BARRIER;case COOLDOWN->Material.GRAY_DYE;};}
    private ItemStack item(Material material,String name,List<String> lore){ItemStack stack=new ItemStack(material==null?Material.BARRIER:material);ItemMeta meta=stack.getItemMeta();meta.displayName(mini.deserialize(name));meta.lore(lore.stream().map(x->mini.deserialize(x)).toList());stack.setItemMeta(meta);return stack;}
    private Component component(String raw,Map<String,String> replacements){return messages.component(raw,replacements);}
}
