database:
  file: quests.db
autosave-interval-seconds: 60
active-quest-limit: 3
gui-click-cooldown-millis: 250
npc-validation-interval-seconds: 30
reach-check-interval-ticks: 20
reach-movement-threshold: 1.0
integrations:
  vault: true
  placeholderapi: true
  mythicmobs: true
quest-resets:
  timezone: Asia/Manila
