package com.questkeeper.quest.service;

import com.questkeeper.api.event.*; import com.questkeeper.message.MessageManager; import com.questkeeper.quest.QuestManager; import com.questkeeper.quest.model.*; import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import org.bukkit.persistence.PersistentDataType; import org.bukkit.plugin.java.JavaPlugin; import java.util.*; import java.util.concurrent.ConcurrentHashMap;

public final class QuestClaimService {
    private final JavaPlugin plugin; private final QuestManager quests; private final PlayerQuestDataService data; private final QuestStateService states; private final RequirementService requirements; private final MessageManager messages; private final Set<UUID> locks=ConcurrentHashMap.newKeySet();
    public QuestClaimService(JavaPlugin p,QuestManager q,PlayerQuestDataService d,QuestStateService s,RequirementService r,MessageManager m){plugin=p;quests=q;data=d;states=s;requirements=r;messages=m;}
    public boolean accept(Player player,String id){ Quest q=quests.get(id); if(q==null||states.state(player,q)!=QuestStatus.AVAILABLE)return false; int active=(int)data.getOrCreate(player.getUniqueId()).quests().values().stream().filter(r->r.status()==QuestStatus.ACTIVE||r.status()==QuestStatus.READY_TO_CLAIM).count(); if(active>=plugin.getConfig().getInt("active-quest-limit",3)) {messages.send(player,"active-limit",Map.of());return false;} var event=new PlayerQuestAcceptEvent(player,q); Bukkit.getPluginManager().callEvent(event); if(event.isCancelled())return false; var r=data.getOrCreate(player.getUniqueId()).record(id);r.status(QuestStatus.ACTIVE);r.acceptedAt(System.currentTimeMillis());data.getOrCreate(player.getUniqueId()).dirty();data.save(data.getOrCreate(player.getUniqueId()));messages.send(player,"quest-accepted",Map.of("quest",q.displayName()));return true; }
    public boolean cancel(Player player,String id){Quest q=quests.get(id);if(q==null||!q.allowCancel()||states.state(player,q)!=QuestStatus.ACTIVE)return false;var e=new PlayerQuestCancelEvent(player,q);Bukkit.getPluginManager().callEvent(e);if(e.isCancelled())return false;data.getOrCreate(player.getUniqueId()).quests().remove(id);data.getOrCreate(player.getUniqueId()).dirty();data.save(data.getOrCreate(player.getUniqueId()));messages.send(player,"quest-cancelled",Map.of("quest",q.displayName()));return true;}
    public boolean claim(Player player,String id,String npcId){ if(!locks.add(player.getUniqueId()))return false;try{Quest q=quests.get(id);if(q==null||!Objects.equals(q.claimNpc(),npcId)||states.state(player,q)!=QuestStatus.READY_TO_CLAIM||!requirements.meets(player,q)){messages.send(player,"cannot-claim",Map.of());return false;}var event=new PlayerQuestClaimEvent(player,q);Bukkit.getPluginManager().callEvent(event);if(event.isCancelled())return false; if(!hasSpace(player,q)){messages.send(player,"inventory-full",Map.of());return false;}give(player,q);var r=data.getOrCreate(player.getUniqueId()).record(id);r.claimedAt(System.currentTimeMillis());r.completedAt(r.claimedAt());r.status(q.repeatType()==RepeatType.ONE_TIME?QuestStatus.COMPLETED:(q.repeatType()==RepeatType.REPEATABLE?QuestStatus.COOLDOWN:QuestStatus.COMPLETED));r.cooldownUntil(q.repeatType()==RepeatType.REPEATABLE?System.currentTimeMillis()+q.cooldownSeconds()*1000L:0);data.getOrCreate(player.getUniqueId()).dirty();data.save(data.getOrCreate(player.getUniqueId()));Bukkit.getPluginManager().callEvent(new PlayerQuestCompleteEvent(player,q));messages.send(player,"quest-claimed",Map.of("quest",q.displayName()));return true;}finally{Bukkit.getScheduler().runTaskLater(plugin,()->locks.remove(player.getUniqueId()),plugin.getConfig().getLong("gui-click-cooldown-millis",250)/50+1);}}
    private boolean hasSpace(Player p,Quest q){for(var reward:q.rewards())if(reward.type()==RewardType.ITEM){Material m=Material.matchMaterial(reward.value());if(m==null)continue;ItemStack stack=new ItemStack(m,reward.amount());if(p.getInventory().firstEmpty()<0&&!p.getInventory().containsAtLeast(stack,reward.amount()))return false;}return true;}
    private void give(Player p,Quest q){for(var reward:q.rewards())switch(reward.type()){case EXPERIENCE->p.giveExp(reward.amount());case COMMAND->Bukkit.dispatchCommand(Bukkit.getConsoleSender(),reward.value().replace("%player%",p.getName()).replace("%player_uuid%",p.getUniqueId().toString()).replace("%quest_id%",q.id()));case ITEM->{Material m=Material.matchMaterial(reward.value());if(m!=null){ItemStack item=new ItemStack(m,reward.amount());ItemMeta meta=item.getItemMeta();String name=(String)reward.settings().get("name");if(name!=null)meta.displayName(net.kyori.adventure.text.minimessage.MiniMessage.miniMessage().deserialize(name));item.setItemMeta(meta);p.getInventory().addItem(item);}}case MONEY,PERMISSION->plugin.getLogger().warning("Reward " + reward.type() + " requires an optional integration or command configuration.");}}
}
