package com.questkeeper.command;

import com.questkeeper.QuestKeeperPlugin; import com.questkeeper.npc.NpcDefinition; import com.questkeeper.utility.IdValidator; import org.bukkit.*; import org.bukkit.command.*; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.entity.Player; import java.io.File; import java.io.IOException; import java.util.*;
public final class QuestAdminCommand implements CommandExecutor,TabCompleter {private final QuestKeeperPlugin plugin;public QuestAdminCommand(QuestKeeperPlugin p){plugin=p;}public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!s.hasPermission("questkeeper.admin")){s.sendMessage("No permission.");return true;}if(a.length==0){s.sendMessage("/questadmin reload|quest|npc|progress|complete|reset|resetall|debug");return true;}try{switch(a[0].toLowerCase(Locale.ROOT)){case "reload"-> {plugin.reloadQuestKeeper();s.sendMessage("QuestKeeper reloaded.");}case "quest"->quest(s,a);case "npc"->npc(s,a);case "progress"->progress(s,a);case "complete"->complete(s,a);case "reset"->reset(s,a);case "resetall"->resetAll(s,a);case "debug"->debug(s,a);default->s.sendMessage("Unknown subcommand.");}}catch(Exception e){s.sendMessage("Command failed: "+e.getMessage());plugin.getLogger().warning("Admin command failed: "+e.getMessage());}return true;}
private void quest(CommandSender s,String[] a){if(a.length<2){s.sendMessage("quest list|create|validate");return;}switch(a[1]){case "list"->plugin.quests().all().forEach(q->s.sendMessage(q.id()+" - "+q.displayName()));case "create"->{requireId(a[2]);File f=new File(plugin.getDataFolder(),"quests/"+a[2]+".yml");if(f.exists()){s.sendMessage("Already exists.");return;}YamlConfiguration c=new YamlConfiguration();c.set("id",a[2]);c.set("display-name","<gold>New Quest");c.set("description",List.of("<gray>Configure me."));c.set("objectives.kill.type","KILL_ENTITY");c.set("objectives.kill.entity","ZOMBIE");c.set("objectives.kill.amount",1);c.set("objectives.kill.display","<yellow>Kill zombies: <white>%progress%/%required%");c.set("requirements.minimum-level",0);c.set("settings.repeat-type","ONE_TIME");c.set("settings.allow-cancel",true);try{c.save(f);s.sendMessage("Created "+a[2]+"; edit YAML then reload.");}catch(IOException e){throw new IllegalStateException(e);}}case "validate"->{if(plugin.quests().get(a[2])!=null)s.sendMessage("Quest is loaded and valid.");else s.sendMessage("Quest is missing or invalid.");}default->s.sendMessage("Unsupported quest operation.");}}
private void npc(CommandSender s,String[] a)throws IOException{if(a.length<2){s.sendMessage("npc list|create|remove|move|assign|unassign");return;}switch(a[1]){case "list"->plugin.npcs().all().forEach(n->s.sendMessage(n.id()+" - "+n.displayName()));case "create"->{if(!(s instanceof Player p)){s.sendMessage("Players only.");return;}requireId(a[2]);var file=new File(plugin.getDataFolder(),"npcs.yml");var c=YamlConfiguration.loadConfiguration(file);String b="npcs."+a[2];c.set(b+".display-name","<gold>"+a[2]);c.set(b+".profession","NONE");c.set(b+".villager-type","PLAINS");c.set(b+".silent",true);Location l=p.getLocation();c.set(b+".location.world",l.getWorld().getName());c.set(b+".location.x",l.getX());c.set(b+".location.y",l.getY());c.set(b+".location.z",l.getZ());c.set(b+".location.yaw",l.getYaw());c.set(b+".location.pitch",l.getPitch());c.set(b+".greeting",List.of("<yellow>Select a quest if you are prepared."));c.set(b+".quests",List.of());c.save(file);plugin.reloadQuestKeeper();s.sendMessage("Created NPC "+a[2]);}case "remove"->{requireId(a[2]);var file=new File(plugin.getDataFolder(),"npcs.yml");var c=YamlConfiguration.loadConfiguration(file);c.set("npcs."+a[2],null);c.save(file);plugin.reloadQuestKeeper();s.sendMessage("Removed NPC "+a[2]);}case "assign","unassign"->{var file=new File(plugin.getDataFolder(),"npcs.yml");var c=YamlConfiguration.loadConfiguration(file);String b="npcs."+a[2]+".quests";List<String> values=new ArrayList<>(c.getStringList(b));if(a[1].equals("assign")&&!values.contains(a[3]))values.add(a[3]);if(a[1].equals("unassign"))values.remove(a[3]);c.set(b,values);c.save(file);plugin.reloadQuestKeeper();s.sendMessage("Updated NPC quests.");}default->s.sendMessage("Unsupported NPC operation.");}}
private void progress(CommandSender s,String[] a){if(a.length<5){s.sendMessage("/questadmin progress <player> <quest> <objective> <amount>");return;}Player p=Bukkit.getPlayerExact(a[1]);if(p==null){s.sendMessage("Player must be online.");return;}plugin.api().addProgress(p,a[2],a[3],Integer.parseInt(a[4]));s.sendMessage("Progress added.");}
private void complete(CommandSender s,String[] a){Player p=Bukkit.getPlayerExact(a[1]);if(p==null){s.sendMessage("Player must be online.");return;}s.sendMessage(plugin.api().completeQuest(p,a[2])?"Quest completed objectives.":"Unable to complete quest.");}
private void reset(CommandSender s,String[] a){plugin.api().resetQuest(Bukkit.getOfflinePlayer(a[1]).getUniqueId(),a[2]);s.sendMessage("Quest reset.");}
private void resetAll(CommandSender s,String[] a){s.sendMessage("Use reset for each quest; bulk reset is intentionally conservative.");}
private void debug(CommandSender s,String[] a){Player p=Bukkit.getPlayerExact(a[1]);if(p==null){s.sendMessage("Player must be online.");return;}plugin.quests().all().forEach(q->s.sendMessage(q.id()+": "+plugin.api().getPlayerQuestState(p.getUniqueId(),q.id())));}
private void requireId(String id){if(!IdValidator.isValid(id))throw new IllegalArgumentException("invalid id");}
public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1)return List.of("reload","quest","npc","progress","complete","reset","resetall","debug");if(a.length==2&&a[0].equalsIgnoreCase("quest"))return List.of("list","create","validate","edit","delete");if(a.length==2&&a[0].equalsIgnoreCase("npc"))return List.of("list","create","edit","move","remove","assign","unassign");return List.of();}}
